const client=window.supabase.createClient("https://jmqcytijuewpwuyuuvui.supabase.co","sb_publishable_PxgrDYvKti_ortsfOwq5YA_b0tzjP5N");
const rows=document.querySelector("#ride-rows"),state=document.querySelector("#ride-state"),count=document.querySelector("#ride-count"),search=document.querySelector("#ride-search"),offerModal=document.querySelector("#offer-modal"),offerForm=document.querySelector("#offer-form"),offerError=document.querySelector("#offer-error"),offerSubmit=document.querySelector("#submit-offer"),toast=document.querySelector(".toast");let rides=[],selectedRide=null;
document.body.insertAdjacentHTML("beforeend",`<dialog id="reserve-modal"><div class="modal-head"><div><p class="eyebrow">RESERVE A SEAT</p><h2>Who is taking this seat?</h2></div><button class="close" type="button" data-close-reserve aria-label="Close">×</button></div><form id="reserve-form"><p class="reservation-route" id="reservation-route"></p><label>Your name<input name="rider_name" maxlength="50" placeholder="e.g. Maya Lee" required/><small>This name will be visible to others viewing the ride.</small></label><p class="form-error" id="reserve-error" role="alert"></p><div class="form-actions"><button class="text-button" type="button" data-close-reserve>Cancel</button><button class="primary" id="submit-reservation">Reserve seat <span>→</span></button></div></form></dialog>`);
const reserveModal=document.querySelector("#reserve-modal"),reserveForm=document.querySelector("#reserve-form"),reserveError=document.querySelector("#reserve-error"),reserveSubmit=document.querySelector("#submit-reservation");
offerForm.insertAdjacentHTML("afterbegin",'<label>Your name<input name="driver_name" maxlength="50" placeholder="e.g. Jordan Lee" required/><small>This connects the offer to your profile.</small></label>');
function profileId(){let id=localStorage.getItem("campuscarpool_profile_id");if(!id){id=crypto.randomUUID();localStorage.setItem("campuscarpool_profile_id",id)}return id}
async function saveProfile(name){const id=profileId();const{error}=await client.from("campus_profiles").upsert({id,display_name:name},{onConflict:"id"});if(error)throw error;localStorage.setItem("campuscarpool_profile_name",name);return id}
function safe(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}function when(v){const d=new Date(v);return{date:d.toLocaleDateString(undefined,{weekday:"short",month:"short",day:"numeric"}),time:d.toLocaleTimeString(undefined,{hour:"numeric",minute:"2-digit"})}}function message(t,loading=false){state.innerHTML=loading?'<span class="spinner"></span><p>Loading offered rides…</p>':`<p>${safe(t)}</p>`;state.classList.add("show")}function showToast(t){toast.textContent=t;toast.classList.add("show");clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.classList.remove("show"),3000)}
function render(){const term=search.value.trim().toLowerCase();const shown=rides.filter(r=>[r.origin,r.destination].some(v=>v.toLowerCase().includes(term)));rows.innerHTML=shown.map(r=>{const d=when(r.departure_at),full=Number(r.seats_available)<1,people=(r.ride_reservations||[]).map(p=>`<span class="passenger">${safe(p.rider_name)}</span>`).join(""),driver=r.driver,stars=driver&&driver.rating_count?`★ ${Number(driver.rating_average).toFixed(1)} (${driver.rating_count})`:"☆ New";return`<tr><td><span class="destination">${safe(r.origin)} <span class="route-arrow">→</span> ${safe(r.destination)}</span><span class="driver-rating">${safe(driver?.display_name||"Campus driver")} · ${stars}</span></td><td><strong>${safe(d.date)}</strong><span class="date-note">${safe(d.time)}</span></td><td><strong class="${full?"sold-out":""}">${full?"Sold out":`${r.seats_available} seat${r.seats_available===1?"":"s"} open`}</strong><div class="passengers">${people||'<span class="no-passengers">No seats reserved yet</span>'}</div></td><td><span class="price">$${Number(r.price_per_seat).toFixed(0)}</span><small class="place-note">per seat</small></td><td><button class="reserve" data-reserve="${r.id}" ${full?"disabled":""}>${full?"Full":"Reserve seat"}</button></td></tr>`}).join("");state.classList.remove("show");if(!shown.length)message(term?"No rides match your search.":"No rides have been offered yet.");count.textContent=`${shown.length} available ride${shown.length===1?"":"s"}`}
async function load(){message("",true);const{data,error}=await client.from("rides").select("id,origin,destination,departure_at,seats_available,price_per_seat,driver_profile_id,driver:campus_profiles!driver_profile_id(display_name,rating_average,rating_count),ride_reservations(rider_name)").gte("departure_at",new Date().toISOString()).order("departure_at",{ascending:true});if(error){console.error(error);message("Could not load rides. Run supabase.sql, then refresh.");count.textContent="Database setup needed";return}rides=data??[];render()}
function openOffer(){offerForm.reset();offerForm.elements.seats_available.value=1;offerError.classList.remove("show");const n=new Date();n.setMinutes(n.getMinutes()-n.getTimezoneOffset());offerForm.elements.departure_date.min=n.toISOString().slice(0,10);offerForm.elements.departure_date.value=n.toISOString().slice(0,10);offerModal.showModal();offerForm.elements.origin.focus()}
document.querySelectorAll("[data-open-offer]").forEach(b=>b.addEventListener("click",openOffer));document.querySelectorAll("[data-close-offer]").forEach(b=>b.addEventListener("click",()=>offerModal.close()));offerModal.addEventListener("click",e=>{if(e.target===offerModal)offerModal.close()});
offerForm.addEventListener("submit",async e=>{e.preventDefault();offerError.classList.remove("show");const v=new FormData(offerForm),departure=new Date(`${v.get("departure_date")}T${v.get("departure_time")}`);if(departure<=new Date()){offerError.textContent="Choose a future departure time.";offerError.classList.add("show");return}offerSubmit.disabled=true;offerSubmit.textContent="Posting…";try{const id=await saveProfile(v.get("driver_name").trim());const{error}=await client.from("rides").insert({origin:v.get("origin").trim(),destination:v.get("destination").trim(),departure_at:departure.toISOString(),seats_available:Number(v.get("seats_available")),price_per_seat:Number(v.get("price_per_seat")),driver_profile_id:id});if(error)throw error;offerModal.close();showToast("Your ride offer is live!");await load()}catch(error){offerError.textContent=error.message;offerError.classList.add("show")}finally{offerSubmit.disabled=false;offerSubmit.innerHTML='Post ride <span>→</span>'}});
rows.addEventListener("click",e=>{const b=e.target.closest("[data-reserve]");if(!b||b.disabled)return;selectedRide=rides.find(r=>String(r.id)===b.dataset.reserve);reserveForm.reset();reserveError.classList.remove("show");document.querySelector("#reservation-route").textContent=`${selectedRide.origin} → ${selectedRide.destination}`;reserveModal.showModal();reserveForm.elements.rider_name.focus()});
document.querySelectorAll("[data-close-reserve]").forEach(b=>b.addEventListener("click",()=>reserveModal.close()));reserveModal.addEventListener("click",e=>{if(e.target===reserveModal)reserveModal.close()});
reserveForm.addEventListener("submit",async e=>{e.preventDefault();const name=new FormData(reserveForm).get("rider_name").trim();reserveSubmit.disabled=true;reserveSubmit.textContent="Reserving…";try{const id=await saveProfile(name);const{data,error}=await client.rpc("reserve_ride_seat",{ride_id:selectedRide.id,reserving_rider_name:name,reserving_profile_id:id});if(error)throw error;reserveModal.close();showToast(data?"Your seat is reserved!":"Sorry, that ride just filled up.");await load()}catch(error){reserveError.textContent=error.message;reserveError.classList.add("show")}finally{reserveSubmit.disabled=false;reserveSubmit.innerHTML='Reserve seat <span>→</span>'}});
search.addEventListener("input",render);document.querySelector("#ride-refresh").addEventListener("click",load);load();client.channel("rides-live").on("postgres_changes",{event:"*",schema:"public",table:"rides"},load).on("postgres_changes",{event:"*",schema:"public",table:"ride_reservations"},load).subscribe();
