-- Run this once in Supabase Dashboard > SQL Editor.
create table if not exists public.ride_requests (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  rider_name text not null check (char_length(rider_name) between 1 and 50),
  contact_info text not null check (char_length(contact_info) between 1 and 100),
  origin text not null check (char_length(origin) between 1 and 120),
  destination text not null check (char_length(destination) between 1 and 120),
  departure_at timestamptz not null,
  price_offer numeric(8,2) not null check (price_offer between 0 and 1000)
);
alter table public.ride_requests enable row level security;
drop policy if exists "Ride requests are publicly readable" on public.ride_requests;
create policy "Ride requests are publicly readable" on public.ride_requests for select to anon, authenticated using (true);
drop policy if exists "Anyone can post a ride request" on public.ride_requests;
create policy "Anyone can post a ride request" on public.ride_requests for insert to anon, authenticated with check (departure_at > now());
do $$
begin
  alter publication supabase_realtime add table public.ride_requests;
exception
  when duplicate_object then null;
end $$;
